In [ ]:

!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
pd.Series(range(5), index=['a','b','c','d','e'],dtype='float64')

In [ ]:
#  create series using string list tuple and dict 
# pd.Series ("String Series")
# print ("string")

# pd.Series ([1,2,"A",4])
# print(list)

# pd.Series ((1,2,3,4))
# print(tuple)

# pd.Series({1})
# print(dict)

In [ ]:
pd.Series(100,index=range(7))

In [ ]:
s = pd.Series(['sujal','pranav','vishal','sneha'])
s

In [ ]:
s.index

In [ ]:
s.values

In [ ]:
pd.__version__

In [ ]:
s.dtype

In [ ]:
s.ndim

In [ ]:
s.size

In [ ]:
s.shape

In [ ]:
s.str.upper()

In [ ]:
s.str.title()

In [ ]:
d = pd.DataFrame( {
    'name' :['anil shinde','akash patil','sneha pawar', 'vailshali kadam'],
    'age':[20,30,30,25],
    'salary':[90000,120000,750000,45000]
})
d

<!-- -->
d.values

In [ ]:
d.values

In [ ]:
d.index

In [ ]:
d.shape

In [ ]:
d.size

In [ ]:
d.to_numpy()

In [ ]:
d.to_csv('data.csv',index=False)

In [ ]:
d.to_csv('data.excel',index=False)

In [ ]:
d

In [ ]:
# select 1 coln has 4 ways
# d['name']
d.name

In [ ]:
# access a col
d.loc[1:1,['name','salary']]
d.loc[2:3,['name','salary']]

In [ ]:
d.iloc[2:, 1:]

In [ ]:
d['salary'].max()

In [ ]:
d.query('salary==salary.max()')

In [ ]:
d.query('salary==salary>80000')

In [ ]:
d['name'].explode

In [ ]:
d['name'].str.split()

In [ ]:
d['name'].apply(lambda nm:nm.split()[1])[3]

In [ ]:
d

In [ ]:
d['f_name'] = d['name'].apply(lambda nm:nm.split()[0])
d

In [ ]:
d['l_name'] = d['name'].apply(lambda nm:nm.split()[1])
d

In [ ]:
# add new coln with 10% HIKE IN salary 
d['new_salary'] = d['salary'].apply(lambda sal:sal*.1+sal)
d

In [ ]:
#  add col with constant value

d['company'] = 'DYP'
d

In [ ]:
# featue engineering = create new from existing one

In [ ]:
# d.drop('salary',axis=1,inplace=True)

In [ ]:
d

In [ ]:
d.query ('name.str.startswith("a")')

In [ ]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

f = pd.read_csv(path)
f.head()

In [ ]:
f.shift()

In [ ]:
f.info()

In [ ]:
f.isnull().sum()

In [ ]:
f['Club'].fillna('Unknown_Club',inplace=True)
f.isnull().sum()

In [ ]:
f.dropna (inplace=True)

In [ ]:
f.isna().sum()

In [ ]:
f.shape

In [ ]:
f.columns

In [ ]:
f['Preferred Foot']

In [ ]:
f.rename(columns={'Preferred Foot' : 'P_Foot'},inplace=True)

In [ ]:
f.columns

In [ ]:
f.Name

In [ ]:
f.columns

In [ ]:
f.columns.str.replace(' ','_')

In [ ]:
f.columns

In [ ]:
f[:2]

In [ ]:
# fetch records of a player from a perticular club
f['Club'].unique()

In [ ]:
f['Club'].nunique()

In [ ]:
f['Club'].value_counts()

In [ ]:
f.dtypes

In [ ]:
# # obj data type replace with another position data type
# f.select_dtypes(inlcude='object').columns

In [ ]:
# f['club'].values_counts()

In [ ]:
f.query('Club =="Real Madrid" and Age>30')

In [ ]:
f.query('Nationality == "England" and Overall>85')

In [426]:
# 5 unique questions 

# a player from england and overall greater than 85
f.query('Nationality == "England" and Overall>85')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.0
60,202652,R. Sterling,23,England,86,89,Manchester City,56500.0,195.0,Right,3.0,4.0,RW,2015,2023-01-01,5.583333,152.0,108800.0

In [427]:
#  a player from city and potential 90

f.query('Club =="Manchester City" and Potential>90')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
55,222492,L. Sané,22,Germany,86,92,Manchester City,61000.0,195.0,Left,2.0,4.0,LW,2016,2021-01-01,6.000000,165.0,125100.0
56,218667,Bernardo Silva,23,Portugal,86,91,Manchester City,59500.0,180.0,Left,2.0,4.0,RW,2017,2022-01-01,5.666667,141.0,114500.0
156,230666,Gabriel Jesus,21,Brazil,83,92,Manchester City,41000.0,130.0,Right,2.0,4.0,ST,2016,2023-01-01,5.750000,161.0,84100.0

In [428]:
#  player from brazil and position gk
f.query('Nationality == "Brazil" and Position == "GK" ')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
57,210257,Ederson,24,Brazil,86,90,Manchester City,41500.0,125.0,Left,2.0,1.0,GK,2017,2025-01-01,6.166667,190.0,79900.0
81,212831,Alisson,25,Brazil,85,90,Liverpool,36500.0,115.0,Right,3.0,1.0,GK,2018,2024-01-01,6.250000,201.0,72100.0
196,194404,Neto,28,Brazil,83,84,Valencia CF,21000.0,41.0,Right,2.0,1.0,GK,2017,2021-01-01,6.250000,185.0,45700.0
232,230168,Raphaelito Anjos,30,Brazil,82,82,Grêmio,14000.0,32.0,Right,1.0,1.0,GK,2018,2021-01-01,6.250000,187.0,25200.0
564,230312,Gabri Prestão,26,Brazil,79,79,Internacional,9000.0,24.0,Right,1.0,1.0,GK,2018,2021-01-01,6.083333,176.0,17100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12712,242084,Carlos Miguel,21,Brazil,63,75,FC Red Bull Salzburg,525.0,3.0,Right,1.0,1.0,GK,2017,2021-01-01,6.333333,194.0,893.0
13732,244418,João Lopes,22,Brazil,62,68,Santa Clara,300.0,1.0,Right,1.0,1.0,GK,2016,2021-01-01,6.166667,181.0,690.0
13881,242159,Ricardo Friedrich,25,Brazil,62,68,FK Bodø/Glimt,300.0,1.0,Right,1.0,1.0,GK,2017,2019-01-01,6.166667,183.0,435.0
14243,243308,Álex Dos Santos,19,Brazil,61,75,Atlético Madrid,450.0,2.0,Right,1.0,1.0,GK,2018,2019-01-01,6.083333,172.0,1200.0
17059,243750,Gianluca Zanette,21,Brazil,55,66,Vejle Boldklub,120.0,1.0,Right,1.0,1.0,GK,2018,2020-01-01,6.166667,176.0,174.0

In [441]:
# a player from left foot in pr
f.query('Nationality == "Portugal" and P_Foot == "Right" ')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
108,120533,Pepe,35,Portugal,85,85,Beşiktaş JK,9000.0,57.0,Right,4.0,2.0,RCB,2017,2019-01-01,6.166667,179.0,17100.0
114,212198,Bruno Fernandes,23,Portugal,84,88,Sporting CP,40500.0,22.0,Right,2.0,4.0,LCM,2017,2023-01-01,5.833333,152.0,84000.0
120,207566,William Carvalho,26,Portugal,84,86,Real Betis,31500.0,38.0,Right,3.0,3.0,CDM,2018,2023-01-01,6.166667,183.0,68500.0
153,20775,Quaresma,34,Portugal,84,84,Beşiktaş JK,15500.0,80.0,Right,3.0,5.0,RM,2015,2020-01-01,5.750000,148.0,29500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14842,246603,Matis Carvalho,19,Portugal,60,73,Toulouse Football Club,300.0,1.0,Right,1.0,1.0,GK,2018,2019-01-01,6.166667,176.0,788.0
15577,237704,João Virgínia,18,Portugal,59,76,Everton,260.0,2.0,Right,1.0,1.0,GK,2018,2021-01-01,6.250000,176.0,657.0
15587,237966,Paulo Alves,20,Portugal,59,70,Wolverhampton Wanderers,260.0,6.0,Right,1.0,3.0,CM,2018,2020-01-01,5.750000,159.0,546.0
15916,240950,Pedro Gonçalves,20,Portugal,58,74,Wolverhampton Wanderers,280.0,6.0,Right,1.0,3.0,CM,2017,2019-01-01,5.666667,154.0,707.0
16664,245752,Vasco Paciência,18,Portugal,57,74,Boavista FC,220.0,1.0,Right,1.0,3.0,ST,2018,2021-01-01,6.000000,165.0,600.0

In [442]:
# a player from arg height less than 5.8
f.query('Nationality == "Argentina" and Height<5.8 ')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
23,153079,S. Agüero,30,Argentina,89,89,Manchester City,64500.0,300.0,Right,4.0,4.0,ST,2011,2021-01-01,5.666667,154.0,119300.0
142,178562,E. Banega,30,Argentina,84,84,Sevilla FC,29000.0,31.0,Right,3.0,4.0,CDM,2017,2020-01-01,5.750000,157.0,60900.0
151,143076,A. Gómez,30,Argentina,84,84,Atalanta,30000.0,53.0,Right,3.0,4.0,LS,2014,2022-01-01,5.416667,150.0,51000.0
295,184144,N. Gaitán,30,Argentina,82,82,Dalian YiFang FC,21000.0,22.0,Left,3.0,4.0,CAM,2018,2021-01-01,5.666667,146.0,45200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16609,235991,N. Cordero,19,Argentina,57,72,Club Atlético Huracán,220.0,1.0,Right,1.0,2.0,ST,2016,2022-01-01,5.583333,152.0,468.0
16813,245358,A. Cháves,26,Argentina,56,58,Club Atlético Colón,110.0,2.0,Right,1.0,2.0,CM,2018,2019-01-01,5.750000,157.0,173.0
17140,232818,M. Hernández,19,Argentina,55,70,Club Atlético Colón,190.0,1.0,Right,1.0,2.0,CM,2016,2021-01-01,5.666667,146.0,404.0
17177,242074,R. Gómez,16,Argentina,55,76,Belgrano de Córdoba,190.0,1.0,Right,1.0,2.0,RM,2018,2020-01-01,5.583333,143.0,466.0
17861,245726,F. Bustamante,19,Argentina,52,66,Club Atlético Tigre,110.0,1.0,Right,1.0,2.0,RM,2018,2021-01-01,5.500000,143.0,234.0